### ISSUE TITLE
Deadlock when using subscriptions with AkkaHttp or Play adapter

### ISSUE THREAD

**Issue by moonkev** [ghostdogpr/caliban#1341]
I have come across a deadlock while using the AkkaHttp adapter, and confirmed via running the examples from the repository that it also affects the Play adapter (does not affect http4s or zio-http).  The bug manifests when a connection is terminated abruptly (for example a client browser closes without properly initiating a subscription shutdown). The deadlock happens in the akka http adapter here - https://github.com/ghostdogpr/caliban/blob/8f3802dcf1e70f342266cc8f1553bba44da158af/adapters/akka-http/src/main/scala/caliban/AkkaHttpAdapter.scala#L142 when attempting to interrupt a fiber.  
and play adapter (same code essentially) - https://github.com/ghostdogpr/caliban/blob/8f3802dcf1e70f342266cc8f1553bba44da158af/adapters/play/src/main/scala/caliban/PlayAdapter.scala#L134

The following is a stack from a deadlocked thread

```
"default-akka.actor.default-dispatcher-8" #29 prio=5 os_prio=31 cpu=13.22ms elapsed=8.94s tid=0x00007fd0eeacb800 nid=0x930b in Object.wait()  [0x000070000d353000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.2/Native Method)
	- waiting on <merged>(a zio.internal.OneShot)
	at java.lang.Object.wait(java.base@11.0.2/Object.java:328)
	at zio.internal.OneShot.get(OneShot.scala:81)
	- waiting to re-lock in wait() <merged>(a zio.internal.OneShot)
	at zio.Runtime.unsafeRunSync(Runtime.scala:86)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:81)
	at zio.Runtime$Managed.unsafeRunSync(Runtime.scala:233)
	at zio.Runtime.unsafeRun(Runtime.scala:59)
	at zio.Runtime.unsafeRun$(Runtime.scala:58)
	at zio.Runtime$Managed.unsafeRun(Runtime.scala:233)
	at caliban.AkkaHttpAdapter$.$anonfun$convertWebSocketEndpoint$15(AkkaHttpAdapter.scala:142)
	at caliban.AkkaHttpAdapter$$$Lambda$1677/0x0000000800a08840.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$1094/0x000000080077f440.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.2/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.2/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.2/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.2/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.2/ForkJoinWorkerThread.java:177)
```

Eventually, after this happens enough the Akka default dispatcher (unless you configured a separate one) will get starved out.  By default this is the number of cores on your system.  So for example, if you have 8 cores, then after happening 8 times, the Akka thread pool will be starved, and akka http will no longer be able to service requests.

To reproduce, simply run either the AkkaHttp or Play example from the Caliban repository.  Using some client like altair and make a subscription.  Then simply close or refresh your browser.  If you take a thread dump, you will see the same as above.  If you do it enough times you'll eventually no longer be able to make requests.

This was tried with Caliban 1.3.3 + Oracle JDK 11 on Windows 10/RHEL 8 and Caliban 1.4.0 + Oracle JDK 18 on macOS Monterey

**Comment by ghostdogpr** [comment]
Just posted a fix in discord, can you confirm it works for you?

**Comment by ghostdogpr** [comment]
Closed by https://github.com/ghostdogpr/caliban/pull/1342
