### ISSUE TITLE
Both `NaiveTest` and `OptimizedTest` optimization examples seem broken

### ISSUE THREAD

**Issue by satorg** [ghostdogpr/caliban#1753]
###### `example.optimizations.NaiveTest`:
```
sbt:caliban> examples/runMain example.optimizations.NaiveTest
[info] running (fork) example.optimizations.NaiveTest 
[info] timestamp=2023-06-05T20:55:11.838106Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.NullPointerException: Cannot invoke "caliban.schema.Schema.toType_(boolean, boolean)" because "this.ev$2" is null
[info] 	at caliban.schema.GenericSchema$$anon$6.toType(Schema.scala:293)
[info] 	at caliban.schema.Schema.caliban$schema$Schema$$asType(Schema.scala:40)
```
###### `example.optimizations.OptimizedTest`:
```
sbt:caliban> examples/runMain example.optimizations.OptimizedTest
[info] running (fork) example.optimizations.OptimizedTest 
[info] timestamp=2023-06-05T21:00:11.834833Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.NullPointerException: Cannot invoke "caliban.schema.Schema.toType_(boolean, boolean)" because "this.ev$2" is null
[info] 	at caliban.schema.GenericSchema$$anon$6.toType(Schema.scala:293)
[info] 	at caliban.schema.Schema.caliban$schema$Schema$$asType(Schema.scala:40)
```

**Comment by satorg** [comment]
The rootcause seems to be recursive schema definitions between the `User` and `Event` models.

@ghostdogpr I can take on fixing the examples if you don't mind.

**Comment by ghostdogpr** [comment]
Thanks for reporting, I just fixed it!
